{"uuid":"47ce4c4a-ac77-4f2d-b871-616e55cfd2fd","historyId":"95384ccec04eb31606572799916bfae1","fullName":"base.Base.initServer","labels":[{"name":"package","value":"tests.T001_ChangeLogBanner"},{"name":"testClass","value":"tests.T001_ChangeLogBanner"},{"name":"testMethod","value":"initServer"},{"name":"parentSuite","value":"Default Suite"},{"name":"suite","value":"apidemos_appium"},{"name":"subSuite","value":"tests.T001_ChangeLogBanner"},{"name":"host","value":"INTELLIGENT"},{"name":"thread","value":"16336@INTELLIGENT.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"},{"name":"AS_ID","value":"-1"}],"links":[],"name":"initServer","status":"broken","statusDetails":{"known":false,"muted":false,"flaky":false,"message":"[The local appium server has not been started, Reason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 30001 ms, Consider increasing the server startup timeout value (currently 30000ms), Node.js executable path: C:\\Program Files\\nodejs\\node.exe, Arguments: [C:\\Users\\aliul\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1], Output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v2.0.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n[debug] \u001B[35m[Appium]\u001B[39m Requiring driver at C:\\Users\\aliul\\.appium\\node_modules\\appium-uiautomator2-driver\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n[debug] \u001B[35m[Appium]\u001B[39m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n[debug] \u001B[35m[Appium]\u001B[39m     at Server.setupListenHandle [as _listen2] (node:net:1740:16)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at listenInCluster (node:net:1788:12)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at doListen (node:net:1937:7)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at processTicksAndRejections (node:internal/process/task_queues:83:21)\r\n]","trace":"io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: [The local appium server has not been started, Reason: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 30001 ms, Consider increasing the server startup timeout value (currently 30000ms), Node.js executable path: C:\\Program Files\\nodejs\\node.exe, Arguments: [C:\\Users\\aliul\\AppData\\Roaming\\npm\\node_modules\\appium\\build\\lib\\main.js, --port, 4723, --address, 127.0.0.1], Output: \u001B[35m[Appium]\u001B[39m Welcome to Appium v2.0.0\r\n\u001B[35m[Appium]\u001B[39m Non-default server args:\r\n\u001B[35m[Appium]\u001B[39m { address: \u001B[32m'127.0.0.1'\u001B[39m }\r\n\u001B[35m[Appium]\u001B[39m Attempting to load driver uiautomator2...\r\n[debug] \u001B[35m[Appium]\u001B[39m Requiring driver at C:\\Users\\aliul\\.appium\\node_modules\\appium-uiautomator2-driver\r\n\u001B[38;5;0m[HTTP]\u001B[0m Could not start REST http interface listener. The requested port may already be in use. Please make sure there is no other instance of this server running already.\r\n\u001B[35m[Appium]\u001B[39m Could not configure Appium server. It's possible that a driver or plugin tried to update the server and failed. Original error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n[debug] \u001B[35m[Appium]\u001B[39m Error: listen EADDRINUSE: address already in use 127.0.0.1:4723\r\n[debug] \u001B[35m[Appium]\u001B[39m     at Server.setupListenHandle [as _listen2] (node:net:1740:16)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at listenInCluster (node:net:1788:12)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at doListen (node:net:1937:7)\r\n[debug] \u001B[35m[Appium]\u001B[39m     at processTicksAndRejections (node:internal/process/task_queues:83:21)\r\n]\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:202)\r\n\tat base.Base.initServer(Base.java:31)\r\n\tat java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)\r\n\tat java.base/java.lang.reflect.Method.invoke(Method.java:578)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)\r\n\tat org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)\r\n\tat org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)\r\n\tat org.testng.SuiteRunner.privateRun(SuiteRunner.java:382)\r\n\tat org.testng.SuiteRunner.run(SuiteRunner.java:336)\r\n\tat org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)\r\n\tat org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)\r\n\tat org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)\r\n\tat org.testng.TestNG.runSuitesLocally(TestNG.java:1200)\r\n\tat org.testng.TestNG.runSuites(TestNG.java:1114)\r\n\tat org.testng.TestNG.run(TestNG.java:1082)\r\n\tat com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)\r\n\tat com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)\r\nCaused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://127.0.0.1:4723/status] to be available after 30001 ms\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:94)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:157)\r\n\tat io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:181)\r\n\t... 17 more\r\nCaused by: java.util.concurrent.TimeoutException\r\n\tat java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)\r\n\tat org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:91)\r\n\t... 19 more\r\n"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1692000767826,"stop":1692000767829}